Models/AlunoModel.cs
using WebAlunos.ViewModels;

namespace WebAlunos.Models
{
    public class AlunoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string CPF { get; set; }
        public string Email { get; set; }
        public bool Deficiencia { get; set; }
        public bool NecessidadesEspeciais { get; set; }
        public string Sexo { get; set; }

        public static explicit operator AlunoModel(AlunoViewModel alunoModel)
        {
            var alunoViewModel = new AlunoModel();
            {
                alunoViewModel.Nome = alunoModel.Nome;
                alunoViewModel.Sobrenome = alunoModel.Sobrenome;
                alunoViewModel.CPF = alunoModel.CPF;
                alunoViewModel.Email = alunoModel.Email;
                alunoViewModel.Deficiencia = alunoModel.Deficiencia;
                alunoViewModel.NecessidadesEspeciais = alunoModel.NecessidadesEspeciais;
                alunoViewModel.Sexo = alunoModel.Sexo;
            };
            return alunoViewModel;
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebAlunos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/AlunoViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebAlunos.Models;

namespace WebAlunos.ViewModels
{
        public class AlunoViewModel
        {
            [Required]
            [MaxLength(100)]
            public string Nome { get; set; }
            
            [Required]
            [MaxLength(100)]
            public string Sobrenome { get; set; }

            [Required]
            [MaxLength(11)]
            public string CPF { get; set; }

            [Required]
            [MaxLength(50)]
            public string Email { get; set; }
            
            public bool Deficiencia { get; set; }
            
            public bool NecessidadesEspeciais { get; set; }
            
            [Required]
            public string Sexo { get; set; }

            public static explicit operator AlunoViewModel(AlunoModel alunoModel)
            {
                var alunoViewModel = new AlunoViewModel();
                {
                    alunoViewModel.Nome = alunoModel.Nome;
                    alunoViewModel.Sobrenome = alunoModel.Sobrenome;
                    alunoViewModel.CPF = alunoModel.CPF;
                    alunoViewModel.Email = alunoModel.Email;
                    alunoViewModel.Deficiencia = alunoModel.Deficiencia;
                    alunoViewModel.NecessidadesEspeciais = alunoModel.NecessidadesEspeciais;
                    alunoViewModel.Sexo = alunoModel.Sexo;
                };
                return alunoViewModel;
            }
        }
}

Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebAlunos.Data;
using WebAlunos.Models;
using WebAlunos.ViewModels;

namespace WebAlunos.Controllers
{
    public class AlunoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly WebAlunosContext _dbContext;
        
        public AlunoController(ILogger<HomeController> logger, WebAlunosContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult CadastroAluno()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CadastroAluno(AlunoViewModel alunoVw)
        {
            if(ModelState.IsValid)
            {
                AlunoModel alunoModel = (AlunoModel)alunoVw; //Também pode ser feito utilizando autoMapper
                
                _dbContext.Add(alunoModel);
                _dbContext.SaveChanges();
            }
            else
            {
                return View(alunoVw);
            }
            
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebAlunos.Models;

namespace WebAlunos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Aluno/CadastroAluno.cshtml
@model WebAlunos.ViewModels.AlunoViewModel

@{
    ViewData["Title"] = "Cadastro de alunos";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="~/images/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Cadastro de alunos</h2>
      <p class="lead">Formulário para cadastro de alunos.</p>
    </div>

    <div class="row g-5">
      <div class="col-md-12">
        <h4 class="mb-3">Dados pessoais</h4>
        <form asp-controller="Aluno" asp-action="CadastroAluno" method="POST" id="formCadastro" class="needs-validation" novalidate="">
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">Primeiro nome</label>
              <input asp-for="@Model.Nome" type="text" class="form-control" id="firstName" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Informe um nome válido.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Sobrenome</label>
              <input asp-for="@Model.Sobrenome" type="text" class="form-control" id="lastName" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Informe um sobrenome válido.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">CPF:</label>
              <div class="input-group has-validation">
                <input asp-for="@Model.CPF" type="text" class="form-control" id="username" placeholder="000.000.000-00" required="">
              <div class="invalid-feedback">
                  CPF é requerido.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Opicional)</span></label>
              <input asp-for="@Model.Email" type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Por favor, informe um endereço de e-mail válido.
              </div>
            </div>

          <hr class="my-4">

          <div class="form-check">
            <input asp-for="@Model.Deficiencia" type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Possuo deficiência física</label>
          </div>

          <div class="form-check">
            <input asp-for="@Model.NecessidadesEspeciais" type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Possuo outras necessidades especiais</label>
          </div>
		  
		  <hr class="my-4">
          <h4 class="mb-3">Sexo</h4>

          <div class="my-3">
            <div class="form-check">
              <input asp-for="@Model.Sexo" id="masculino" name="sexo" type="radio" value="M" class="form-check-input" checked="" required="">
              <label class="form-check-label" for="masculino">Masculino</label>
            </div>
            <div class="form-check">
              <input asp-for="@Model.Sexo" id="feminino" name="sexo" type="radio" value="F" class="form-check-input" required="">
              <label class="form-check-label" for="feminino">Feminino</label>
            </div>
          </div>
		  
		  <hr class="my-4">
			<h4 class="mb-3">Endereço</h4>
			
            <div class="col-12">
              <label for="address" class="form-label">Endereço</label>
              <input type="text" class="form-control" id="address" placeholder="Rua Bahia, 1234" required="">
              <div class="invalid-feedback">
                Por favor, informe seu endereço.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Endereço 2 <span class="text-muted">(Opcional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Rua Henrique Pegoli, 1125">
            </div>
			
			<div class="col-md-4">
              <label for="state" class="form-label">Estado</label>
              <select class="form-select" id="state" required="">
                <option value="">Selecione...</option>
                <option value="SP">São Paulo</option>
				<option value="RJ">Rio de Janeiro</option>
              </select>
              <div class="invalid-feedback">
                Por favor, selecione um estado.
              </div>
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Cidade</label>
              <select class="form-select" id="country" required="">
                <option value="">Selecione...</option>
                <option value="Campinas">Campinas</option>
				<option value="Valinhos">Valinhos</option>
              </select>
              <div class="invalid-feedback">
                Por favor, escolha uma cidade.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">CEP:</label>
              <input type="text" class="form-control" id="zip" placeholder="00000-000" required="">
              <div class="invalid-feedback">
                O campo CEP é requerido.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Confirmar cadastro</button>
        </form>
      </div>
    </div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAlunos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/form-validation.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAlunos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="CadastroAluno">Cadastro de alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-light">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAlunos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/form-validation.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>